services:
  mysql:
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=sa'
      - 'MYSQL_ROOT_PASSWORD=pass'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306'